### ISSUE TITLE
TypeError: require(...).main is not a function

### ISSUE THREAD

**Issue by prvnsmpth** [microsoft/lsif-node#122]
I ran into a TypeError while attempting to run the indexer after installing the lsif-tsc package. I installed it using `npm install -g lsif-tsc`. This installed version 0.5.3.

After successful installation, attempts to run the lsif-tsc command fail with the following error:
```
~
❯ lsif-tsc 
/usr/local/lib/node_modules/lsif-tsc/bin/lsif-tsc:2
require('../lib/main.js').main().then(undefined, console.error);
                          ^

TypeError: require(...).main is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/lsif-tsc/bin/lsif-tsc:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```
I checked `main.js`, and found that it doesn't export a function called `main()`. Am I missing something here?

Node version:
```
~
❯ node --version 
v12.18.3
```

**Comment by dbaeumer** [comment]
Sorry, I broke this. You can work around it by install `npm install -g lsif` which installs all `lsif` related tooling and then run `lsif tsc` (e.g. without a dash). Will look into fixing this

**Comment by dbaeumer** [comment]
Fixed. Published new version.
