### ISSUE TITLE
TypeError: Optional options.transfer argument must be an iterable

### ISSUE THREAD

**Issue by connor4312** [microsoft/lsif-node#190]
1. Clone https://github.com/websockets/ws
2. Create a simple jsonconfig.json

```
{
  "compilerOptions": {
    "target": "ES2021"
  }
}
```

3. Run `npx -y lsif-tsc --out lsif.json  --noContents --workspaceRoot ./ --package -p jsconfig.json`
4. See the error:

```
TypeError: Optional options.transfer argument must be an iterable
    at Worker.postMessage (node:internal/worker:371:5)
    at Connection._sendNotification (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/common/connection.js:73:19)
    at FileWriter.writeBuffer (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/common/writer.js:84:29)
    at FileWriter.writeln (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/common/writer.js:66:18)
    at Object.emit (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/emitters/line.js:8:20)
    at Object.emit (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/main.js:613:21)
    at DataManager.emit (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/lsif.js:2561:22)
    at DocumentData.emit (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/lsif.js:157:23)
    at DocumentData.end (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/lsif.js:292:18)
    at DataManager.documentProcessed (/home/connor/.npm/_npx/ee23f37870d9c921/node_modules/lsif-tsc/lib/lsif.js:2731:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by dbaeumer** [comment]
Seems to be fixed

```
npx -y lsif-tsc --out lsif.json  --noContents --workspaceRoot ./ --package -p jsconfig.json
........................................
Processed 4554 symbols in 40 files for project file:///home/dirkb/Projects/mseng/VSCode/Playgrounds/bugs/ws/jsconfig.json (file:///home/dirkb/Projects/mseng/VSCode/Playgrounds/bugs/ws/jsconfig.json) in 2265ms.


Processed 157 symbols in 0 files for project Machine default libraries in 2250ms.


Processed 98 symbols in 20 files for project TypeScript default libraries in 2259ms.
```
