### ISSUE TITLE
npm-lsif fails in version 0.1.0

### ISSUE THREAD

**Issue by jepetty** [microsoft/lsif-node#23]
Running the tsc-lsif and npm-lsif tools version 0.1.0 fails on certain typescript repos with the following error:
> ..\node_modules\npm-lsif\lib\main.js:104
>        let outUri = this.mapToOut(document.uri);
>                                            ^
>
> TypeError: Cannot read property 'uri' of undefined
     at ExportLinker.exports (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\npm-lsif\lib\main.js:104:45)
    at Interface.rd.on (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\npm-lsif\lib\main.js:255:34)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:280:10)
    at Interface._normalWrite (readline.js:422:12)
    at Socket.ondata (readline.js:139:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
events.js:183
      throw er; // Unhandled 'error' event
      ^
>
> Error: EPIPE: broken pipe, write
    at Socket._write (internal/net.js:23:7)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at Object.emit (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\tsc-lsif\lib\emitters\line.js:14:19)
    at Visitor.emit (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\tsc-lsif\lib\lsif.js:1321:22)
    at Visitor.endVisitSourceFile (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\tsc-lsif\lib\lsif.js:1070:22)
    at Visitor.doVisit (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\tsc-lsif\lib\lsif.js:994:18)
    at Visitor.visit (C:\VSCloudKernel.jepetty\bin\LSIFLanguageServer\Debug\netcoreapp2.1\node_modules\tsc-lsif\lib\lsif.js:954:22)

The repo/pull request this repros on is https://github.com/vsls-contrib/pomodoro/pull/3/files and the command used to invoke the tools is `node ..\tsc-lsif\lib\main.js -p C:\pomodoro\tsconfig.json --outputFormat=line | node .\lib\main.js -p C:/pomodoro/package.json`

**Comment by dbaeumer** [comment]
@jepetty works for me using latest on master. Produces

[lsif.txt](https://github.com/Microsoft/lsif-typescript/files/2962351/lsif.txt)

which commit is the tool on you are using.

**Comment by dbaeumer** [comment]
@jepetty are you still seeing this?

**Comment by jepetty** [comment]
Closing as no longer reproducing
