### ISSUE TITLE
LSIF TSC emitter crash with TypeScript error

### ISSUE THREAD

**Issue by mostafaeweda** [microsoft/lsif-node#35]
Running LSIF on `vscode` source code crashed with an error:
```
TypeError: Cannot read property 'kind' of undefined
    at pipelineEmitWithHint (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:83854:39)
    at print (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:83754:13)
    at Object.writeNode (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:83614:13)
    at /Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:107880:50
    at Object.mapToDisplayParts (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:96944:13)
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:107878:61)
    at /Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:121297:41
    at Object.runWithCancellationToken (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:31434:28)
    at Object.getQuickInfoAtPosition (/Users/most/Code/lsif-node/tsc/node_modules/typescript/lib/typescript.js:121296:34)
    at Visitor.getHover (/Users/most/Code/lsif-node/tsc/lib/lsif.js:1447:46)
```
<img width="1463" alt="Screenshot 2019-05-01 12 20 23" src="https://user-images.githubusercontent.com/264320/57040328-ef828e80-6c13-11e9-9d9b-963e94380244.png">

That was reproducible over the code: `...args: TS` in https://github.com/Microsoft/vscode/blob/b2cd559eb1481e220c587f044a514b475e3c6a1e/src/vs/platform/instantiation/common/instantiation.ts#L98

I've worked around by adding `try/catch` and `return undefined` in `lsif.ts` `Visitor.getHover`

Before I send a PR, I'm wondering if the emitter should be resilient to the underlying language service errors.

**Comment by dbaeumer** [comment]
This is what I do right now as well.

**Comment by dbaeumer** [comment]
https://github.com/microsoft/lsif-node/blob/master/tsc/src/lsif.ts#L3535
