### ISSUE TITLE
"Already managed document data" error

### ISSUE THREAD

**Issue by arjun27** [microsoft/lsif-node#49]
@dantup reported the following error while using lsif-tsc 0.4.1 on the [Dart-Code repo](https://github.com/Dart-Code/Dart-Code). See full logs here: [output.txt](https://github.com/microsoft/lsif-node/files/3311610/output.txt)

```
Error: There was already a managed document data for file: /Users/dantup/Dev/Dart-Code/src/shared/analysis_server_types.ts
    at DataManager.getDocumentData (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:910:19)
    at Visitor.getOrCreateDocumentData (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1298:39)
    at Visitor.getOrCreateSymbolData (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1333:37)
    at TypeAliasResolver.resolve (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:802:58)
    at result.dataManager.getOrCreateSymbolData (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1347:148)
    at DataManager.getOrCreateSymbolData (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:942:22)
    at Visitor.getOrCreateSymbolData (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1346:35)
    at Visitor.visitIdentifier (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1265:31)
    at Visitor.visit (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1073:22)
    at node.forEachChild.child (/Users/dantup/.npm-global/lib/node_modules/lsif-tsc/lib/lsif.js:1076:49)
```

**Steps to repro**

1. Verify that lsif-tsc 0.4.1 is installed 
2. Clone the https://github.com/Dart-Code/Dart-Code repo
3. Run `lsif-tsc -p ./tsconfig.json` from the repo directory

Unfortunately, when I try to repro with lsif-tsc 0.4.1, I'm running into a different error, full logs here: [full-logs.txt](https://github.com/microsoft/lsif-node/files/3311627/full-logs.txt).

```
TypeError: sourceFiles.values(...) is not a function or its return value is not iterable
    at Visitor.getOrCreateSymbolData (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/lib/lsif.js:1332:44)
    at Visitor.visitIdentifier (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/lib/lsif.js:1265:31)
    at Visitor.visit (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/lib/lsif.js:1073:22)
    at node.forEachChild.child (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/lib/lsif.js:1076:49)
    at visitNode (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/node_modules/typescript/lib/typescript.js:16622:24)
    at Object.forEachChild (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/node_modules/typescript/lib/typescript.js:16975:24)
    at NodeObject.forEachChild (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/node_modules/typescript/lib/typescript.js:121404:23)
    at Visitor.visit (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/lib/lsif.js:1076:22)
    at node.forEachChild.child (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/lib/lsif.js:1076:49)
    at visitNode (/Users/arjun/.nvm/versions/node/v9.11.1/lib/node_modules/lsif-tsc/node_modules/typescript/lib/typescript.js:16622:24)
```

Hope this helps!

**Comment by dbaeumer** [comment]
Fixed in 0.4.6
