### ISSUE TITLE
Tried running lsif-tsc and it crashed

### ISSUE THREAD

**Issue by mtaran-google** [microsoft/lsif-node#63]
I was running it over an internal codebase and it printed dots and then crashed with the following stack:

```
Error: Partition for symbol QKQAbLXLFhLyVyj6S2I7+g== have already been cleared
    at StandardSymbolData.getOrCreatePartition (/node_modules/lsif-tsc/lib/lsif.js:352:19)
    at AliasedSymbolData.addReference (/node_modules/lsif-tsc/lib/lsif.js:454:22)
    at Visitor.handleSymbol (/node_modules/lsif-tsc/lib/lsif.js:1546:20)
    at Visitor.visitIdentifier (/node_modules/lsif-tsc/lib/lsif.js:1527:14)
    at Visitor.visit (/node_modules/lsif-tsc/lib/lsif.js:1321:22)
    at node.forEachChild.child (/node_modules/lsif-tsc/lib/lsif.js:1334:45)
    at visitNode (/node_modules/typescript/lib/typescript.js:16622:24)
    at Object.forEachChild (/node_modules/typescript/lib/typescript.js:16986:24)
    at NodeObject.forEachChild (/node_modules/typescript/lib/typescript.js:121434:23)
    at Visitor.doVisit (/node_modules/lsif-tsc/lib/lsif.js:1334:18)
```

**Comment by dbaeumer** [comment]
This got addressed in the latest version.
