### ISSUE TITLE
Lsif-tsc 0.4.9 fails on reactivex/rxjs

### ISSUE THREAD

**Issue by efritz** [microsoft/lsif-node#69]
Running lsif-tsc over the rxjs repository causes the following error, in which a document has already been finalized but is seen again. I have not investigated this deeply yet, but it seems as if the set of files it iterates over contains duplicates (I see some effort to de-duplicate this, but for transitive files there is no such effort).

**Steps to Reproduce**:

- Clone reactivex/rxjs
- Run `npm i`
- Run `lsif-tsc`

**Output**:

```
$ lsif-tsc -p tsconfig.json --out temp.lsif --noContents
...................................................................................................................................................................................................................................................................................................................................................................................................Error: There was already a managed document data for file: /Users/efritz/dev/sourcegraph/rxjs/src/internal/util/root.ts
    at DataManager.getDocumentData (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1119:19)
    at Visitor.getOrCreateDocumentData (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1597:39)
    at Visitor.getOrCreateSymbolData (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1643:37)
    at AliasResolver.resolve (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:927:58)
    at /usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1657:148
    at DataManager.getOrCreateSymbolData (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1152:22)
    at Visitor.getOrCreateSymbolData (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1656:35)
    at Visitor.handleSymbol (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1536:31)
    at Visitor.visitIdentifier (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1527:14)
    at Visitor.visit (/usr/local/lib/node_modules/lsif-tsc/lib/lsif.js:1321:22)
```

**Comment by dbaeumer** [comment]
@efritz thanks for the report. Was able to reproduce can will have a look.

**Comment by dbaeumer** [comment]
Published 0.4.10.

@efritz out of curiosity: what is the use case of running the lsif tool over the rxjs code?

**Comment by efritz** [comment]
Just looking for popular typescript projects to test the exporter on. Is it an odd use-case to run the tool over rxjs?

**Comment by dbaeumer** [comment]
No, not at all. What other projects did you test so far

**Comment by efritz** [comment]
We also ran it on vscode and some internal libraries/projects.
