### ISSUE TITLE
[lsif-tsc] fails on vsls-contrib/pomodoro with node 8.x

### ISSUE THREAD

**Issue by jepetty** [microsoft/lsif-node#73]
Using node v8.2.0 and 8.9.3, lsif-tsc fails with the following output:

{"id":1,"type":"vertex","label":"metaData","version":"0.4.3","projectRoot":"file:///c:/VSCloudKernel.jepetty/bin/RichCodeNav.LSIF/Debug/netcoreapp2.1/node_modules/lsif-tsc/lib","positionEncoding":"utf-16"}
{"id":2,"type":"vertex","label":"project","kind":"typescript"}
{"id":3,"type":"vertex","label":"$event","kind":"begin","scope":"project","data":2}
{"id":4,"type":"vertex","label":"document","uri":"file:///c:/pomodoro/src/IAppState.ts","languageId":"typescript","contents":"ZXhwb3J0IGludGVyZmFjZSBJQXBwU3RhdGUgew0KICAgIHJlbWFpbmluZ1RpbWU6IG51bWJlcjsNCiAgICBzdGF0ZTogSVN0YXRlOw0KICAgIGNvbXBsZXRlZFNlZ21lbnRzOiBudW1iZXI7DQogICAgY29uZmlnOiBJUG9tb2Rvcm9Db25maWc7DQp9DQoNCmV4cG9ydCBpbnRlcmZhY2UgSVN0YXRlIHsNCiAgICBpc1BhdXNlZDogYm9vbGVhbjsNCiAgICBpc0JyZWFrOiBib29sZWFuOw0KICAgIGlzRmluaXNoZWQ6IGJvb2xlYW47DQp9DQoNCmV4cG9ydCBpbnRlcmZhY2UgSVBvbW9kb3JvQ29uZmlnIHsNCiAgICBicmVha0R1cmF0aW9uOiBudW1iZXI7DQogICAgaW50ZXJ2YWxDb3VudDogbnVtYmVyOw0KICAgIGludGVydmFsRHVyYXRpb246IG51bWJlcjsNCiAgICBsb25nQnJlYWtEdXJhdGlvbjogbnVtYmVyOw0KfQ0KDQpleHBvcnQgY29uc3QgU1RBUlRfQUNUSU9OID0gJ3N0YXJ0JzsNCmV4cG9ydCBjb25zdCBTVE9QX0FDVElPTiA9ICdzdG9wJzsNCmV4cG9ydCBjb25zdCBSRVNFVF9BQ1RJT04gPSAncmVzZXQnOw0KZXhwb3J0IGNvbnN0IFBBVVNFX0FDVElPTiA9ICdwYXVzZSc7DQpleHBvcnQgY29uc3QgVVBEQVRFX1JFTUFJTklOR19USU1FX0FDVElPTiA9ICd1cGRhdGUucmVtYWluaW5nLnRpbWUnOw0KDQpleHBvcnQgZnVuY3Rpb24gc3RhcnRBY3Rpb24oKSB7DQogICAgcmV0dXJuIHsNCiAgICAgICAgdHlwZTogU1RBUlRfQUNUSU9ODQogICAgfTsNCn0NCg0KZXhwb3J0IGZ1bmN0aW9uIHN0b3BBY3Rpb24oKSB7DQogICAgcmV0dXJuIHsNCiAgICAgICAgdHlwZTogU1RPUF9BQ1RJT04NCiAgICB9Ow0KfQ0KDQpleHBvcnQgZnVuY3Rpb24gcGF1c2VBY3Rpb24ocmVtYWluaW5nVGltZTogbnVtYmVyKSB7DQogICAgcmV0dXJuIHsNCiAgICAgICAgdHlwZTogUEFVU0VfQUNUSU9OLA0KICAgICAgICByZW1haW5pbmdUaW1lDQogICAgfTsNCn0NCg0KZXhwb3J0IGZ1bmN0aW9uIHJlc2V0QWN0aW9uKCkgew0KICAgIHJldHVybiB7DQogICAgICAgIHR5cGU6IFJFU0VUX0FDVElPTg0KICAgIH07DQp9DQo="}
{"id":5,"type":"vertex","label":"$event","kind":"begin","scope":"document","data":4}
<b>TypeError: sourceFiles.values is not a function
    at Visitor.getOrCreateSymbolData (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1721:44)
    at Visitor.getOrCreateDocumentData (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1696:18)
    at Visitor.visitSourceFile (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1430:33)
    at Visitor.doVisit (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1371:19)
    at Visitor.visit (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1325:22)
    at Visitor.visitProgram (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1312:18)
    at Object.lsif (C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\lsif.js:1923:26)
    at C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\main.js:202:23
    at Generator.next (<anonymous>)
    at C:\VSCloudKernel.jepetty\bin\RichCodeNav.LSIF\Debug\netcoreapp2.1\node_modules\lsif-tsc\lib\main.js:7:71</b>

I've verified that it works with node v.10.16.3. Is there a required version of node to run lsif-tsc?

**Comment by jepetty** [comment]
Closing this as it seems by design and we've advised consumers to upgrade CI Machines
