### ISSUE TITLE
Local Symbol data has more than one partition

### ISSUE THREAD

**Issue by chrismwendt** [microsoft/lsif-node#76]
When running `lsif-tsc` on https://github.com/sourcegraph/sourcegraph, I got an error:

```
lsif-tsc -p web --noContents --out data.lsif
.........................................................................................................................................................................................................................................................................................................................Error: Local Symbol data has more than one partition.
    at StandardSymbolData.nodeProcessed (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:382:23)
    at DataManager.nodeProcessed (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1208:32)
    at Visitor.doVisit (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1374:26)
    at Visitor.visit (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1325:22)
    at Visitor.visitProgram (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1312:18)
    at Object.lsif (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1923:26)
    at /Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/main.js:202:23
    at Generator.next (<anonymous>)
    at /Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/main.js:7:71
    at new Promise (<anonymous>)
```

I believe sharding was added in https://github.com/microsoft/lsif-node/commit/12ecfc7e2680c53712b14583e5a8d3b1dc59423c. See https://github.com/microsoft/lsif-node/issues/39.

cc @dbaeumer

**Comment by dbaeumer** [comment]
Underlying issue is: https://github.com/microsoft/lsif-node/issues/116

**Comment by dbaeumer** [comment]
Got addressed in master
