### ISSUE TITLE
Error: There was already a managed document data for file

### ISSUE THREAD

**Issue by chrismwendt** [microsoft/lsif-node#84]
When running `node /Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/main.js --noContents --out=dump.lsif -p .` (using https://github.com/sourcegraph/lsif-node/tree/e71e4db3b05895f4d88a64c7f3d5558621460622) on https://github.com/sourcegraph/sourcegraph/tree/85297b68a966c41576aaba10f16f5b7048ee007c/web

```
..................................................................................................Error: There was already a managed document data for file: /Users/chrismwendt/github.com/sourcegraph/sourcegraph/shared/src/globals.d.ts
    at DataManager.getDocumentData (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1161:19)
    at Visitor.getOrCreateDocumentData (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1681:39)
    at Visitor.getOrCreateSymbolData (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1727:37)
    at Visitor.handleSymbol (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1620:31)
    at Visitor.visitIdentifier (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1611:14)
    at Visitor.visit (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1364:22)
    at /Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/lib/lsif.js:1377:45
    at visitNode (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/node_modules/typescript/lib/typescript.js:16622:24)
    at Object.forEachChild (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/node_modules/typescript/lib/typescript.js:16802:24)
    at NodeObject.forEachChild (/Users/chrismwendt/github.com/Microsoft/lsif-node/tsc/node_modules/typescript/lib/typescript.js:121434:23)
```

Possibly related https://github.com/microsoft/lsif-node/issues/49

**Comment by chrismwendt** [comment]
Repro:

```
$ tail -n +1 *
==> file.ts <==
declare var x: number

==> file2.ts <==
console.log(x)


==> tsconfig.json <==
{}
$ lsif-tsc --noContents --out=dump.lsif -p .
..Error: There was already a managed document data for file: /Users/chrismwendt/lsif-tsc-manager-data/file.ts
    at DataManager.getDocumentData (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1156:19)
    at Visitor.getOrCreateDocumentData (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1676:39)
    at Visitor.getOrCreateSymbolData (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1722:37)
    at Visitor.handleSymbol (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1615:31)
    at Visitor.visitIdentifier (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1606:14)
    at Visitor.visit (/Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1359:22)
    at /Users/chrismwendt/.config/yarn/global/node_modules/lsif-tsc/lib/lsif.js:1372:45
    at visitNodes (/Users/chrismwendt/.config/yarn/global/node_modules/typescript/lib/typescript.js:16631:30)
    at Object.forEachChild (/Users/chrismwendt/.config/yarn/global/node_modules/typescript/lib/typescript.js:16811:21)
    at NodeObject.forEachChild (/Users/chrismwendt/.config/yarn/global/node_modules/typescript/lib/typescript.js:121434:23)
```

**Comment by jepetty** [comment]
We're hitting this problem as well in a number of repos we're trying to onboard (~30/87 repos seem to be hitting it).

**Comment by efritz** [comment]
I have a draft of a fix in our fork: https://github.com/sourcegraph/lsif-node/pull/5. I doubt that this is a sufficient general solution as it does muck up the order of document end events (which may be important for some editor-based usage).

@jepetty I'm curious to hear if this fix solves the problem on some of your repos as well.

**Comment by xuachen** [comment]
@efritz Thanks for your fix. I have tried it again on some repos with your fork and it works. Is there any plan on merging fixes there to this repo? I am from the same team as @jepetty and we consume the latest https://www.npmjs.com/package/lsif-tsc package @0.4.10, so would be great if we could update to a version with the fix but without pulling many other additional changes.

**Comment by efritz** [comment]
@xuachen Glad it helped! We were for a few months making changes that would only be upstreamable, but unfortunately it doesn't look like this projects is interested in accepting them. Open issues/pull requests opened between September and February (see https://github.com/microsoft/lsif-node/issues/75, https://github.com/microsoft/lsif-node/pull/89, https://github.com/microsoft/lsif-node/pull/81, https://github.com/microsoft/lsif-node/pull/71, https://github.com/microsoft/lsif-node/pull/66). We've since decided to just maintain our own indexer.

**Comment by dbaeumer** [comment]
@xuachen can you point me to a repository that shows this behaviour?

**Comment by dbaeumer** [comment]
@efritz sorry for this but somehow I somehow didn't receive notification for this repository anymore. I will have a look and see what the problems are.

**Comment by efritz** [comment]
@dbaeumer The original issue description gives a repo and rev hash that does this, and @chrismwendt gave a minimal two-file reproduction in this thread.

**Comment by dbaeumer** [comment]
@efritz: is this the case: https://github.com/microsoft/lsif-node/issues/75

**Comment by dbaeumer** [comment]
Sorry, I see now: https://github.com/microsoft/lsif-node/issues/84#issuecomment-568088347

**Comment by xuachen** [comment]
@dbaeumer One repo I was testing was: https://github.com/expressjs/express and we manually add a jsconifg.json with `{"compilerOptions": {"checkJs": true},"exclude": ["node_modules","node","dist","out","webpack","webpack-dev-server","ember","jspm"]}
`
Some other repos with the same issue (we create jsconfig.json with the same content as above if they don't have one): https://github.com/request/request, https://github.com/visionmedia/debug, https://github.com/petkaantonov/bluebird

**Comment by dbaeumer** [comment]
@xuachen using the tool on a pure JS repository without a jsconfig.json will be very hard since it is very unclear what the project files are. How did you start the tool without the jsconfig.json?

**Comment by xuachen** [comment]
@dbaeumer We manually add a new jsconfig.json file to the repo root with content: `{"compilerOptions": {"checkJs": true},"exclude": ["node_modules","node","dist","out","webpack","webpack-dev-server","ember","jspm"]}` 
and invoke the tool with path to the jsconfig.json: `$lsif-tsc -p ./express/jsconfig.json --stdout`

This actually works to give us index but have the managed document error for some documents. Do you have suggestions on how to index these repos properly instead?

**Comment by dbaeumer** [comment]
I started looking into this and @chrismwendt example uses global modules which are currently not supported. Will look into this.

**Comment by dbaeumer** [comment]
@xuachen can you provide me with a concrete example when the managed document data happens. The problem with this is that it happens when the tool is not handling a special TS construct correctly. So I need a case to understand the underlying problem.

**Comment by xuachen** [comment]
@dbaeumer going back to all the repos that hit this issue I found they were actually all pure JS repositories without jsconfig.json as you said, so I guess they were not supposed to be working.

An example to repro:
1. Clone https://github.com/expressjs/express
2. Add `{"compilerOptions": {"checkJs": true},"exclude": ["node_modules","node","dist","out","webpack","webpack-dev-server","ember","jspm"]}` to a jsconfig.json file at repo root
3. `$lsif-tsc -p ./express/jsconfig.json --stdout`

Maybe this is a wrong jsconfig.json issue, but would like to know if there is a way to work around it to index the repo correctly.
