### ISSUE TITLE
Error: Either path or symbol must be provided.

### ISSUE THREAD

**Issue by jepetty** [microsoft/lsif-node#87]
lsif-tsc fails on some repositories with the following error:
```
Error: Either path or symbol must be provided.
    at Object.createMonikerIdentifier (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\typescripts.js:69:19)
    at Visitor.getOrCreateSymbolData (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1747:36)
    at Visitor.getOrCreateDocumentData (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1696:18)
    at Visitor.visitSourceFile (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1430:33)
    at Visitor.doVisit (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1371:19)
    at Visitor.visit (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1325:22)
    at Visitor.visitProgram (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1312:18)
    at Object.lsif (C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\lsif.js:1923:26)
    at C:\Users\jepetty\AppData\Roaming\npm\node_modules\lsif-tsc\lib\main.js:202:23
    at Generator.next (<anonymous>)
```
Failing repos/tsconfigs:
- https://github.com/aws/aws-sdk-js -> aws-sdk-js/ts/tsconfig.json
- https://github.com/vuejs/vue -> vue\types\test\tsconfig.json
- winstonjs/winston -> winston\tsconfig.json
- https://github.com/microsoft/typescript -> typescript\scripts\tsconfig.json

PS I'm using node v10.16.3

**Comment by jepetty** [comment]
@dbaeumer is this expected to be fixed in the 0.5 release? We had an internal partner hit this and are wondering if there are any mitigation strategies that we can perform. 😊

**Comment by dbaeumer** [comment]
@jepetty it should be fixed with the latest version. Does the internal partner still sees this with the latest version?
